name: Node.js
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Install required apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev
    - name: Run Snyk to check for vulnerabilities
      if: ${{ env.GITHUB_EVENT_NAME == "mmarkelov/jest-playwright" }}
      uses: snyk/actions/node@master
    - name: Lint Source Code
      run: npm run lint
    - name: Build project
      run: npm run build
    - name: Run tests
      run: npm run test
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
